#!/usr/bin/env bash

if command_exists cargo; then
  alias cr="cargo run"
  alias cb="cargo build"
  alias ct="cargo test"
fi

if [ -d $HOME/.rvm ]; then
  export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
  export PATH="$PATH:$HOME/.cargo/bin" # Add Rust cargo to PATH
fi
