#!/usr/bin/env bash

function _portkill_help {
  echo "Usage: $1 <port>\n"
  echo "Kills applications using provided port."
}

function _portkill_kill_listener {
  local listener
  lsof -i:$1 | awk -v LISTEN="(LISTEN)" '$10 == LISTEN { print $0 }' | while read line; do
    listener=$line
  done

  if [ -z "$listener" ]; then
    echo "No process listening on port $1"
  else
    local process=$(echo $listener | awk '{ print $1 }')
    local pid=$(echo $listener | awk '{ print $2 }')
    local user=$(echo $listener | awk '{ print $3 }')
    echo "Killing process $process (pid: $pid) of user $user."
    kill -TERM $pid || kill -KILL $pid
  fi
}

function portkill {
  if [ "$#" -eq 0 ]; then
    _portkill_help "$0"
  else
    _portkill_kill_listener $1
  fi
}

